spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
      location: C:\\upload
      enabled: true

  datasource:
    url: jdbc:mysql://springsecurity.cdmamjvzddrb.us-east-1.rds.amazonaws.com/b01
    username: admin
    password: akf5705l!

  jpa:
    hibernate:
      ddl-auto: update
      #??2 ddl ?? ???? ?? ??? none?? validate ??, ?? ??? update, create ? ????.
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-id: Rest API 키
            client-secret: 비밀키
            client-authentication-method: POST
            scope: profile_nickname,account_email

#??1 show-sql, format_sql ??? sql ??? ?? ??? ?? ??? ??? ?.

logging:
  level:
    org:
      springframework: info
      springframework.security: trace
      zerock: debug


org:
  zerock:
    upload:
      path: C:\\upload
